<?php if (!defined('S3_PROPOSALS_AUTHORIZED')) { http_response_code(404); exit; } ?>
<!doctype html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#111111">
  <meta name="description" content="Crie propostas comerciais com vários serviços, coberturas de eventos e condições de pagamento para a S3 Mídia.">
  <title>Propostas | S3 Mídia</title>
  <link rel="icon" type="image/png" href="/admin/brand/mark-black.png">
  <style>
    :root{font-family:Inter,Arial,sans-serif;color:#171717;background:#f6f6f4;font-size:16px;--ink:#111;--muted:#70706d;--line:#e6e6e2;--surface:#fff}
    *{box-sizing:border-box}body{margin:0;background:radial-gradient(ellipse at 92% 0%,#e9e9e6 0,transparent 28%),#f6f6f4}button,input,select,textarea{font:inherit}button{cursor:pointer}
    .top{background:linear-gradient(115deg,#101010 0%,#181818 58%,#242424 100%);color:white;padding:13px max(22px,calc((100vw - 1480px)/2));display:flex;align-items:center;justify-content:space-between;gap:16px;min-height:76px;box-shadow:0 1px 0 #ffffff12 inset}.brandLogo{display:block;width:168px;height:60px;object-fit:contain;object-position:left center}.top small{color:#bdbdb9;font-size:.8rem;letter-spacing:.04em}
    .tabs{max-width:1480px;margin:0 auto;padding:20px 22px 0;display:flex;gap:5px;border-bottom:1px solid var(--line)}.tab{border:0;border-bottom:2px solid transparent;background:transparent;color:#666;padding:12px 15px 11px;font-size:.96rem;font-weight:650;min-height:46px;transition:color .18s ease,border-color .18s ease}.tab:hover{color:#111}.tab[aria-selected="true"]{color:#111;border-bottom-color:#111}.tab:focus-visible{outline:2px solid #555;outline-offset:2px}
    .catalogLayout{max-width:1060px;margin:0 auto;padding:25px 22px 70px}.catalogHead{background:linear-gradient(115deg,#111 0%,#202020 100%);color:white;border-radius:12px;padding:24px 27px;margin-bottom:18px;box-shadow:0 12px 30px #11111112}.catalogHead h1{margin-bottom:7px}.catalogHead p{margin:0;color:#d4d4d0;line-height:1.5}.catalogGrid{display:grid;grid-template-columns:260px minmax(0,1fr);gap:16px;align-items:start}.catalogNav{position:sticky;top:16px}.catalogForm .stack{margin-bottom:16px}.catalogForm h2{margin-top:20px}.catalogForm .eventBox{margin-bottom:16px}.catalogStatus{font-size:.87rem;color:#383838;min-height:18px}
    .layout{max-width:1480px;margin:auto;display:grid;grid-template-columns:minmax(350px,550px) minmax(0,1fr);gap:22px;padding:22px 22px 70px}
    h1{font-size:1.7rem;letter-spacing:-.04em;margin:0 0 7px}h2{font-size:1.13rem;letter-spacing:-.025em;margin:0 0 16px}h3{font-size:1rem;margin:0 0 12px}
    .muted{color:#5d6559;line-height:1.48}.intro{margin:0 0 22px}
    .panel,.service{background:var(--surface);border:1px solid var(--line);border-radius:12px;box-shadow:0 5px 22px #11111108}.panel{padding:22px}.service{padding:18px;margin:13px 0;transition:border-color .18s ease,box-shadow .18s ease}.service:hover{border-color:#d1d1cc;box-shadow:0 7px 24px #1111110c}
    .serviceHead{display:flex;align-items:start;justify-content:space-between;gap:10px;margin-bottom:17px}.serviceHead h3{margin:0}.serviceHead small{display:block;color:#687064;font-size:.79rem;margin-top:4px}
    .stack{display:grid;gap:14px;margin-bottom:16px}.two{grid-template-columns:repeat(2,minmax(0,1fr))}.three{grid-template-columns:repeat(3,minmax(0,1fr))}
    .field{display:flex;flex-direction:column;gap:7px;min-width:0}label,.label{font-size:.94rem;font-weight:680}
    input,select,textarea{width:100%;border:1px solid #d8d8d4;border-radius:6px;background:#fff;color:#1d1d1b;padding:10px 11px;line-height:1.38;outline:none;min-height:42px}
    input:focus,select:focus,textarea:focus{border-color:#555;box-shadow:0 0 0 3px #11111112}textarea{min-height:72px;resize:vertical}
    .hint{font-size:.86rem;line-height:1.5;color:#687064;margin:5px 0 0}.divider{border:0;border-top:1px solid #e1e6dc;margin:23px 0}
    .btn{border:1px solid #d3d3cf;background:white;color:#171717;border-radius:7px;padding:9px 13px;min-height:41px;font-weight:650;transition:transform .16s ease,box-shadow .16s ease,background-color .16s ease}.btn.primary{background:#111;border-color:#111;color:#fff}.btn.danger{color:#852f25;border-color:#e2c6c1}.btn:hover{filter:brightness(.97);transform:translateY(-1px);box-shadow:0 4px 12px #11111112}.btn:active{transform:translateY(0);box-shadow:none}.btn:focus-visible{outline:2px solid #555;outline-offset:2px}
    .actions{display:flex;gap:9px;flex-wrap:wrap}.smallBtn{border:0;background:transparent;text-decoration:underline;color:#47583b;font-weight:700;padding:5px;font-size:.82rem}
    .check{display:flex;gap:9px;align-items:center;font-size:.9rem;font-weight:700}.check input{width:18px;height:18px;min-height:0;margin:0}
    .eventBox{background:#fafaf9;border:1px solid #e5e5e1;border-radius:7px;padding:15px;margin:12px 0 15px}
    .eventBox h4{margin:0 0 11px;font-size:.92rem}.eventBox .hint{margin-bottom:13px}
    .economics{background:#f7f7f5;border:1px solid #e5e5e1;border-radius:6px;padding:10px 12px;font-size:.8rem;line-height:1.45;margin:8px 0 14px}.economics.warn{background:#faf4f2;border-color:#ead5d0}.economics strong{display:block}
    #status{min-height:19px;margin:10px 0 0;font-size:.85rem;color:#333}
    .previewWrap{position:sticky;top:18px;align-self:start}.previewLabel{display:flex;justify-content:space-between;font-weight:700;color:#5f695c;font-size:.81rem;margin-bottom:9px}
    .paper{position:relative;isolation:isolate;background:white;border:1px solid var(--line);border-radius:9px;padding:34px clamp(24px,3.5vw,48px);min-height:0;overflow-wrap:anywhere;box-shadow:0 18px 60px #17171712}.paper>:not(.paperWatermark){position:relative;z-index:1}.paperWatermark{position:absolute;z-index:0;top:50%;left:50%;right:auto;bottom:auto;transform:translate(-50%,-50%);width:110px;height:auto;opacity:.025;pointer-events:none;user-select:none}.coverPage{position:relative;display:flex;flex-direction:column;justify-content:space-between;gap:28px;min-height:900px;padding:42px clamp(24px,4vw,50px) 28px;overflow:hidden;background:linear-gradient(180deg,#fff 0%,#fff 76%,#f7f7f5 100%);border-bottom:1px solid #e5e5e1}.coverPage:before{content:"";position:absolute;top:0;left:0;width:100%;height:7px;background:#111}.coverHeader,.coverHero,.coverBottom{position:relative;z-index:1}.coverHeader{display:flex;align-items:center;justify-content:space-between;gap:16px;padding-bottom:17px;border-bottom:1px solid var(--line)}.coverLogo{display:block;flex:0 1 190px;width:190px;height:72px;object-fit:contain;object-position:left center}.coverBrandTag{text-align:right;color:#666;font-size:.66rem;line-height:1.55;font-weight:750;letter-spacing:.12em}.coverHero{padding:32px 0 28px;max-width:650px}.coverKicker{display:inline-block;padding-left:10px;border-left:3px solid #111;color:#666;font-size:.7rem;letter-spacing:.13em;font-weight:800}.coverHero h1{font-size:clamp(2.3rem,4vw,3.25rem);line-height:1.02;letter-spacing:-.055em;margin:17px 0 13px;overflow-wrap:anywhere}.coverHero h1 span{display:block;color:#555;margin-top:5px}.coverIntro{max-width:540px;color:#555;font-size:.98rem;line-height:1.58;margin:0}.coverScope{margin-top:28px;padding-top:14px;border-top:1px solid #deded9}.coverScope small,.coverFact small{display:block;color:#777;font-size:.66rem;font-weight:800;letter-spacing:.12em}.coverServices{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.coverServiceTag{padding:6px 9px;border:1px solid #e0e0dc;border-radius:4px;background:#f5f5f2;color:#252523;font-size:.8rem;line-height:1.25}.coverBottom{display:grid;gap:15px}.coverFacts{display:grid;grid-template-columns:1.35fr 1fr 1fr;background:#f3f3f0;border:1px solid #e5e5e1;border-radius:7px;overflow:hidden}.coverFact{min-width:0;padding:12px 13px}.coverFact+.coverFact{border-left:1px solid #dfdfda}.coverFact strong{display:block;margin-top:5px;color:#171717;font-size:.9rem;line-height:1.35;overflow-wrap:anywhere}.coverFooter{display:flex;justify-content:space-between;gap:12px;border-top:1px solid #deded9;padding-top:10px;color:#777;font-size:.7rem;line-height:1.4;letter-spacing:.02em}.coverFooter span:last-child{text-align:right}
    .paperTop{display:flex;align-items:center;justify-content:space-between;gap:20px;width:100%;border-bottom:1px solid #111;padding-bottom:18px}.paperLogo{display:block;flex:0 1 172px;width:172px;height:80px;object-fit:contain;object-position:left center}.meta{display:flex;flex-direction:column;align-items:flex-end;gap:5px;text-align:right;color:#62625f;font-size:.84rem;line-height:1.4;letter-spacing:.03em}.meta strong{color:#111;font-size:.9rem;letter-spacing:.075em}.meta span{display:block}
    .eyebrow{text-transform:uppercase;color:#777;font-size:.76rem;letter-spacing:.1em;font-weight:750;margin:30px 0 10px}
    .paper h2{font-size:1.8rem;letter-spacing:-.045em;line-height:1.12;margin:0 0 7px}.paper p{line-height:1.52;margin:5px 0 0}.client{font-size:.98rem;color:#555}
    .summary{border-left:2px solid #111;padding:8px 12px;margin:15px 0;background:#fafaf9}.summary h3{display:none}
    .quoteItem{border-top:1px solid #e5e5e1;padding:13px 0;break-inside:avoid}.quoteItem h3{font-size:1rem;letter-spacing:-.015em;margin:0 0 3px}.quoteItem .description{color:#454542;font-size:.88rem}
    .quoteItem ul{font-size:.85rem;line-height:1.4;margin:6px 0;padding-left:17px}.quoteItem li{margin:2px 0}.eventDetails{color:#444;font-size:.8rem;line-height:1.4;margin-top:5px;white-space:normal}
    .tableScroll{overflow-x:auto}.quoteTable{width:100%;border-collapse:collapse;table-layout:fixed;font-size:.91rem}.quoteTable th{background:#f5f5f3;color:#555;text-align:left;text-transform:uppercase;letter-spacing:.045em;font-size:.75rem;font-weight:750;padding:10px 10px;border-bottom:1px solid #dcdcd8}.quoteTable td{vertical-align:top;padding:13px 10px;border-bottom:1px solid #e7e7e3;overflow-wrap:anywhere}.quoteTable th:nth-child(1){width:40%}.quoteTable th:nth-child(2){width:22%}.quoteTable th:nth-child(3){width:12%}.quoteTable th:nth-child(4){width:13%}.quoteTable th:nth-child(5){width:13%}.quoteTable.noDiscount th:nth-child(1){width:40%}.quoteTable.noDiscount th:nth-child(2){width:22%}.quoteTable.noDiscount th:nth-child(3){width:19%}.quoteTable.noDiscount th:nth-child(4){width:0}.quoteTable.noDiscount th:nth-child(5){width:19%}.quoteTable .serviceCell h3{font-size:1rem;margin:0 0 4px}.quoteTable .serviceCell p{font-size:.88rem;color:#555;margin:4px 0}.quoteTable ul{font-size:.86rem;line-height:1.42;margin:5px 0;padding-left:18px}.quoteTable li{margin:2px 0}.quoteTable .eventDetails{font-size:.83rem;line-height:1.42;margin-top:5px}.quoteTable .conditionCell{font-size:.86rem;line-height:1.5;color:#555;white-space:pre-line}.quoteTable .amountCell,.quoteTable .discountCell,.quoteTable .finalCell{font-size:.88rem;line-height:1.45}.quoteTable .finalCell strong{font-size:.98rem;color:#111}.quoteTable del{display:block;color:#858581}.quoteTable .discountLabel{display:block;font-size:.84rem;color:#333;font-weight:650;margin-top:3px}.quoteTable .period{display:block;font-size:.78rem;color:#555}
    .itemBottom{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:16px;margin-top:13px;align-items:end}.price{font-size:1.57rem;font-weight:850;letter-spacing:-.035em;white-space:nowrap}
    .fine{color:#5d5d59;font-size:.78rem;line-height:1.4;white-space:pre-line}.totals{background:linear-gradient(115deg,#111 0%,#202020 100%);color:white;padding:13px 16px;margin:12px 0 16px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;border-radius:7px;break-inside:avoid;box-shadow:0 7px 18px #11111112}
    .totals small{display:block;color:#d1d1cd;font-size:.7rem;margin-bottom:3px}.totals strong{font-size:1.15rem}.terms{border-top:1px solid #e5e5e1;padding-top:11px;margin-top:12px;white-space:pre-line}.terms h3{font-size:.88rem;margin:0}.terms p{font-size:.78rem}.footer{border-top:1px solid #e5e5e1;padding-top:9px;margin-top:16px;color:#777;font-size:.7rem;line-height:1.4}
    .historyLayout{max-width:1050px;margin:0 auto;padding:24px 22px 70px}.historyItem{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:14px;align-items:center;border-bottom:1px solid var(--line);padding:15px 0}.historyItem h3{margin:0 0 4px}.historyMeta{font-size:.82rem;color:var(--muted);line-height:1.5}.historyActions{display:flex;gap:7px;flex-wrap:wrap}.emptyHistory{padding:25px;border:1px dashed #d6d6d1;border-radius:8px;color:var(--muted);text-align:center}
    .aiLayout{max-width:950px;margin:auto;padding:25px 22px 70px}.aiLayout textarea{min-height:180px}.aiResult{margin-top:18px}.aiCard{background:#f6f8f2;border:1px solid #dde5d4;border-radius:8px;padding:15px;margin:12px 0}.aiCard h3{margin:0 0 8px}.aiCard p{margin:5px 0;line-height:1.5}.aiWarning{color:#8c492e}.aiStatus{min-height:20px;margin:12px 0;line-height:1.5}
    [hidden]{display:none!important}
    @media(max-width:1050px){.layout{grid-template-columns:1fr}.previewWrap{position:static}}
    @media(max-width:680px){.catalogGrid{grid-template-columns:1fr}.catalogNav{position:static}}
    @media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;transition-duration:.01ms!important;animation-duration:.01ms!important;animation-iteration-count:1!important}}
    @media(max-width:600px){.top{padding:10px 15px;min-height:64px}.brandLogo{width:142px;height:52px}.top small{display:none}.tabs{padding:10px 7px 0;overflow-x:auto}.tab{flex:0 0 auto;padding:10px 11px;font-size:.9rem}.layout,.catalogLayout,.aiLayout,.historyLayout{padding:14px 11px}.panel,.service{padding:16px}.two,.three{grid-template-columns:1fr}.paper{padding:22px 17px}.coverPage{min-height:720px;padding:27px 22px 20px;gap:18px}.coverLogo{width:142px;height:58px}.coverBrandTag{font-size:.56rem}.coverHero{padding:16px 0}.coverHero h1{font-size:2.2rem}.coverIntro{font-size:.88rem}.coverScope{margin-top:18px}.coverFacts{grid-template-columns:1fr}.coverFact{padding:9px 11px}.coverFact+.coverFact{border-left:0;border-top:1px solid #dfdfda}.coverFooter{font-size:.63rem}.paper h2{font-size:1.55rem}.paperLogo{width:112px;height:60px}.paperWatermark{width:76px}.itemBottom{grid-template-columns:1fr}.price{white-space:normal}.historyItem{grid-template-columns:1fr}}
    @media print{@page{size:A4;margin:4mm 12mm}body{background:white;-webkit-print-color-adjust:exact;print-color-adjust:exact;font-size:9.5pt}.top,.tabs,.editor,.previewLabel,#catalogTab,#aiTab,#historyTab{display:none!important}#proposalTab{display:block!important;padding:0;max-width:none}.previewWrap{position:static}.paper{border:0;border-radius:0;padding:0;min-height:0;font-size:9.5pt;box-shadow:none}.coverPage{height:289mm;min-height:289mm;padding:13mm 12mm 10mm;gap:0;border:0;break-after:page;page-break-after:always;background:white}.coverHeader{padding-bottom:7mm}.coverLogo{flex-basis:48mm;width:48mm;height:19mm}.coverBrandTag{font-size:7pt}.coverHero{padding:0;margin:auto 0;width:100%}.coverKicker{font-size:7pt}.coverHero h1{font-size:30pt;margin:8mm 0 4mm}.coverIntro{font-size:10pt;max-width:135mm}.coverScope{margin-top:10mm;padding-top:4mm}.coverScope small,.coverFact small{font-size:7pt}.coverServices{gap:2mm;margin-top:3mm}.coverServiceTag{font-size:8.5pt;padding:2mm 3mm}.coverBottom{gap:4mm}.coverFacts{grid-template-columns:1.35fr 1fr 1fr}.coverFact{padding:3mm}.coverFact strong{font-size:9pt}.coverFooter{font-size:7.5pt;padding-top:3mm}.paperWatermark{position:fixed;top:50%;left:50%;right:auto;bottom:auto;transform:translate(-50%,-50%);width:96px;opacity:.025}.paperTop{padding-bottom:9mm}.paperLogo{flex-basis:138px;width:138px;height:64px}.paperTop{width:100%;padding-bottom:9mm}.meta{font-size:8pt}.meta strong{font-size:8.5pt}.paper h2{font-size:18pt;margin-bottom:3mm}.eyebrow{margin:7mm 0 3mm;font-size:7.5pt}.summary{margin:8px 0;padding:5px 9px}.paper p,.client{font-size:9pt}.tableScroll{overflow:visible}.quoteTable{min-width:0;font-size:8.5pt}.quoteTable thead{display:table-header-group}.quoteTable tr{break-inside:avoid;page-break-inside:avoid}.quoteTable th{font-size:7.4pt;padding:7px 6px}.quoteTable td{padding:8px 6px}.quoteTable .serviceCell h3{font-size:9.5pt}.quoteTable .serviceCell p,.quoteTable ul,.quoteTable .conditionCell,.quoteTable .eventDetails{font-size:8pt;line-height:1.35}.quoteTable .amountCell,.quoteTable .discountCell,.quoteTable .finalCell{font-size:8.5pt}.quoteTable .discountLabel,.quoteTable .period{font-size:8pt}.quoteTable .finalCell strong{font-size:9pt}.totals{padding:8px 10px;margin:8px 0 9px;box-shadow:none}.totals small{font-size:8pt}.totals strong{font-size:11pt}.terms{padding-top:7px;margin-top:8px}.terms p{font-size:8.5pt}.footer{margin-top:9px;padding-top:6px;font-size:8pt}}
  </style>
</head>
<body>
<?php $activeArea = "propostas"; require __DIR__ . "/navigation.php"; ?>
  <header class="top"><img class="brandLogo" src="/admin/brand/logo-white.png" alt="S3 Mídia Marketing e Publicidade"><small>Propostas comerciais</small></header>
  <nav class="tabs" role="tablist" aria-label="Áreas do gerador"><button class="tab" role="tab" id="tabProposal" aria-selected="true" aria-controls="proposalTab" type="button">Montar proposta</button><button class="tab" role="tab" id="tabCatalog" aria-selected="false" aria-controls="catalogTab" type="button">Serviços e preços</button><button class="tab" role="tab" id="tabAI" aria-selected="false" aria-controls="aiTab" type="button">Criar com IA</button><button class="tab" role="tab" id="tabHistory" aria-selected="false" aria-controls="historyTab" type="button">Histórico <span id="historyCount"></span></button></nav>
  <main class="layout" id="proposalTab" role="tabpanel" aria-labelledby="tabProposal">
    <section class="editor" aria-label="Editor de proposta">
      <div class="panel"><h1>Monte a proposta</h1><p class="muted intro">Combine serviços, defina cobrança por item e personalize as condições. A prévia ao lado é atualizada enquanto você escreve.</p>
        <div class="stack two"><div class="field"><label for="client">Empresa ou cliente</label><input id="client" placeholder="Ex.: Maria e João / Empresa Exemplo"></div><div class="field"><label for="contact">Contato (opcional)</label><input id="contact" placeholder="Ex.: Maria Silva"></div></div>
        <div class="stack"><div class="field"><label for="location">Local principal do serviço (opcional)</label><input id="location" placeholder="Ex.: Barreiras – BA, remoto ou local do evento"><p class="hint">Se ficar vazio, o gerador aproveita o local informado nos serviços de cobertura.</p></div></div>
        <div class="stack"><div class="field"><label for="intro">Texto de apresentação da proposta</label><textarea id="intro" rows="3"></textarea><p class="hint">O texto começa com uma sugestão ligada aos serviços escolhidos. Você pode editar livremente.</p></div></div>
        <div class="stack two"><div class="field"><label for="validity">Validade da proposta (dias)</label><input id="validity" type="number" min="1" max="90" value="7"></div><div class="field"><label for="generalNotes">Observações gerais (opcional)</label><input id="generalNotes" placeholder="Ex.: deslocamento fora da cidade à parte"></div></div>
      </div>
      <div id="services" aria-label="Serviços incluídos"></div>
      <div class="panel"><h2>Adicionar serviço</h2><div class="stack"><div class="field"><label for="newPreset">Modelo inicial</label><select id="newPreset"></select></div></div><button class="btn primary" id="add" type="button">+ Incluir na proposta</button><p class="hint">Cada item pode ter prazo, preço e condições de pagamento diferentes. Projeto único e mensalidade aparecem em totais separados.</p></div>
      <div class="panel" style="margin-top:14px"><div class="actions"><button class="btn primary" id="print" type="button">Salvar em PDF</button><button class="btn" id="saveHistory" type="button">Salvar no histórico</button><button class="btn" id="copy" type="button">Copiar resumo</button><button class="btn danger" id="clear" type="button">Limpar rascunho</button></div><p id="status" role="status" aria-live="polite"></p><p class="hint">Inclua apenas as entregas e condições combinadas. Confira custos, deslocamento e tributos antes de enviar.</p></div>
    </section>
    <section class="previewWrap" aria-label="Prévia da proposta"><div class="previewLabel"><span>PRÉVIA DA PROPOSTA</span><span>Atualização em tempo real</span></div><article class="paper" id="paper">
      <section class="coverPage" aria-label="Capa de apresentação da proposta">
        <header class="coverHeader"><img class="coverLogo" src="/admin/brand/logo-black.png" alt="S3 Mídia"><div class="coverBrandTag">AGÊNCIA DE MARKETING<br>&amp; PUBLICIDADE</div></header>
        <div class="coverHero"><div class="coverKicker">PROPOSTA COMERCIAL</div><h1>Uma proposta para<span id="coverClient">Seu projeto</span></h1><p class="coverIntro">A S3 Mídia une estratégia, criação e produção para fortalecer marcas e aproximá-las de seus públicos. Este documento reúne um escopo pensado para os objetivos do seu projeto.</p><div class="coverScope"><small>ESCOPO DESTA PROPOSTA</small><div class="coverServices" id="coverServices"></div></div></div>
        <div class="coverBottom"><div class="coverFacts"><div class="coverFact"><small>LOCAL DO SERVIÇO</small><strong id="coverLocation">A combinar com o cliente</strong></div><div class="coverFact"><small>DATA DA PROPOSTA</small><strong id="coverDate"></strong></div><div class="coverFact"><small>IDENTIFICAÇÃO</small><strong id="coverNumber"></strong></div></div><footer class="coverFooter"><span>ESTRATÉGIA · CRIATIVIDADE · EXECUÇÃO</span><span>Barreiras · Luís Eduardo Magalhães/BA<br>s3midiadigital.com.br · @s3midia</span></footer></div>
      </section><img class="paperWatermark" src="/admin/brand/mark-black.png" alt="" aria-hidden="true"><div class="paperTop"><img class="paperLogo" src="/admin/brand/logo-black.png" alt="S3 Mídia Marketing e Publicidade"><div class="meta"><strong>DETALHAMENTO DA PROPOSTA</strong><span id="pNumber"></span></div></div>
      <div class="eyebrow">Proposta para</div><h2 id="pClient"></h2><div class="client" id="pContact"></div>
      <div class="summary"><h3>Uma proposta para o seu projeto</h3><p id="pIntro"></p></div>
      <div class="tableScroll"><table class="quoteTable noDiscount" id="pServicesTable"><thead><tr><th>Serviço e entregas</th><th>Prazo e pagamento</th><th>Valor</th><th id="pDiscountHead" hidden>Desconto</th><th>Total</th></tr></thead><tbody id="pServices"></tbody></table></div><div class="totals" id="pTotals"></div>
      <div class="terms"><h3>Condições gerais</h3><p id="pValidity"></p><p id="pGeneralNotes"></p></div>
      <div class="footer">S3 Mídia · Luís Eduardo Magalhães e Barreiras, BA<br>s3midiadigital.com.br · @s3midia</div>
    </article></section>
  </main>
  <main class="catalogLayout" id="catalogTab" role="tabpanel" aria-labelledby="tabCatalog" hidden>
    <div class="catalogHead"><h1>Serviços e preços</h1><p>Edite os valores e as entregas padrão de cada serviço. Novos itens da proposta usarão o padrão salvo; itens já incluídos permanecem como foram negociados.</p></div>
    <div class="catalogGrid"><aside class="panel catalogNav"><div class="field"><label for="catalogSelect">Escolha um serviço</label><select id="catalogSelect"></select></div><p class="hint">Os valores são sugestões. Confirme equipe, deslocamento, impressão, ferramentas e tempo de edição antes de cobrar.</p><button class="btn" id="restorePreset" type="button" style="margin-top:16px">Restaurar este padrão</button></aside>
      <section class="panel catalogForm"><h2 id="catalogTitle">Editar serviço</h2><div id="catalogFields"></div><p class="catalogStatus" id="catalogStatus" role="status" aria-live="polite"></p></section>
    </div>
  </main>
  <main class="aiLayout" id="aiTab" role="tabpanel" aria-labelledby="tabAI" hidden>
    <section class="panel"><h1>Criar proposta com IA</h1><p class="muted">Descreva o cliente, os serviços, o que será entregue e, se souber, valores, datas e condições de pagamento. A IA prepara um rascunho para você revisar.</p>
      <div class="field"><label for="aiBrief">Resumo do atendimento</label><textarea id="aiBrief" maxlength="6000" placeholder="Ex.: Proposta para Ana e João: cobertura de casamento por 6 horas, fotos tratadas, teaser em vídeo e drone. Entrega em 30 dias. 50% na reserva e 50% antes do evento. Se eu não informar valores, use meus preços padrão."></textarea></div>
      <p class="hint">Se faltar preço, prazo ou pagamento, serão usados os dados da aba Serviços e preços. O resumo e seus padrões serão enviados à IA somente ao clicar em gerar.</p>
      <div class="actions" style="margin-top:17px"><button class="btn primary" id="aiGenerate" type="button">Gerar rascunho com IA</button></div><p class="aiStatus" id="aiStatus" role="status" aria-live="polite"></p>
      <section id="aiResult" class="aiResult" hidden><h2>Confira o rascunho</h2><div id="aiSummary"></div><div id="aiCards"></div><div id="aiWarnings" class="aiWarning"></div><div class="actions" style="margin-top:18px"><button class="btn primary" id="aiReplace" type="button">Usar como nova proposta</button><button class="btn" id="aiAppend" type="button">Adicionar à proposta atual</button></div><p class="hint">Depois, ajuste cada item no editor e confira os valores e as entregas antes de enviar.</p></section>
    </section>
  </main>
  <main class="historyLayout" id="historyTab" role="tabpanel" aria-labelledby="tabHistory" hidden>
    <section class="panel"><h1>Histórico de propostas</h1><p class="muted">Propostas salvas neste navegador. Abra uma cópia para revisar, editar ou imprimir.</p><div id="historyList"></div></section>
  </main>
  <script>
    'use strict';
    const presets=[
      {id:'presenca',name:'Presença digital essencial',title:'Presença digital essencial',price:690,hours:6,costs:0,billing:'unico',deadline:'Até 5 dias úteis após recebimento dos acessos e materiais',description:'Vamos organizar a apresentação digital da empresa para que as informações principais e o caminho de contato estejam claros.',deliverables:'Diagnóstico curto dos canais atuais\nAjuste de bio, destaques e chamada para contato no Instagram\nRevisão das informações públicas no Perfil da Empresa no Google, com acesso fornecido pelo cliente\n3 peças estáticas com legenda',payment:'50% na aprovação e 50% na entrega.',notes:'Não inclui filmagem, gestão diária, anúncios nem verificação do perfil pelo Google.'},
      {id:'landing',name:'Landing page essencial',title:'Landing page essencial',price:1490,hours:12,costs:0,billing:'unico',deadline:'Até 10 dias úteis após briefing e materiais',description:'Uma página objetiva para apresentar sua oferta e facilitar pedidos de orçamento pelo WhatsApp.',deliverables:'1 página responsiva adaptada à identidade existente\nEstrutura e texto-base com informações fornecidas pelo cliente\nBotão de WhatsApp e formulário simples, quando viável na hospedagem\nConfiguração básica de títulos e descrição para buscadores\n2 rodadas de ajustes pontuais',payment:'50% na aprovação e 50% antes da publicação.',notes:'Domínio, hospedagem, ferramentas pagas, integrações complexas e anúncios são pagos à parte.'},
      {id:'social',name:'Conteúdo mensal essencial',title:'Conteúdo mensal para Instagram',price:1290,hours:12,costs:0,billing:'mensal',deadline:'Ciclo mensal; calendário em até 5 dias úteis após briefing',description:'Conteúdo planejado para manter sua marca presente com mensagens claras e uma rotina de publicação sustentável.',deliverables:'Planejamento mensal para 1 perfil\n8 publicações: até 6 peças estáticas e 2 carrosséis curtos\nLegendas e agendamento após aprovação\n1 rodada de ajustes por peça\nResumo mensal de métricas da plataforma',payment:'Mensalidade antecipada no início de cada ciclo.',notes:'O cliente fornece fotos, informações e aprova o calendário. Não inclui filmagem, DMs, stories diários nem verba de anúncios.'},
      {id:'video',name:'Vídeos curtos para redes',title:'Pacote de vídeos curtos',price:1190,hours:10,costs:0,billing:'unico',deadline:'Até 7 dias úteis após a gravação',description:'Vídeos objetivos para mostrar produtos, pessoas e serviços com uma linguagem adequada às redes sociais.',deliverables:'1 sessão de gravação de até 2 horas em Luís Eduardo Magalhães\n4 vídeos verticais de até 45 segundos cada\nEdição simples, legendas básicas e música licenciada disponível\n1 rodada de ajustes por vídeo',payment:'50% para reservar a data e 50% antes da entrega.',notes:'Roteiros complexos, locução, elenco, deslocamento, drone e cobertura de evento são orçados à parte.'},
      {id:'trafego',name:'Gestão de anúncios Meta Ads',title:'Gestão de anúncios Meta Ads',price:1490,hours:12,costs:0,billing:'mensal',deadline:'Configuração em até 7 dias úteis após acessos; acompanhamento mensal',description:'Campanhas focadas em uma oferta e em um caminho de contato, com acompanhamento do investimento e das oportunidades geradas.',deliverables:'Diagnóstico inicial da oferta e do caminho de contato\nConfiguração de até 2 campanhas na Meta\nAté 4 variações simples de criativos com material do cliente\nAjustes semanais e relatório mensal',payment:'Mensalidade antecipada; verba de mídia paga diretamente pelo cliente à Meta.',notes:'Não inclui verba de mídia, landing page, produção audiovisual nem atendimento aos leads. Não há garantia de vendas.'},
      {id:'aniversario',name:'Aniversário · fotografia',title:'Cobertura fotográfica de aniversário',price:1090,hours:10,costs:0,billing:'unico',event:true,eventType:'Aniversário',coverageHours:4,crew:'1 profissional de fotografia',photoCount:100,photos:'Até 100 fotos selecionadas e tratadas, em galeria digital',videos:'',album:'',extraHour:'R$ 220 por hora adicional de cobertura, sujeita à disponibilidade',eventDelivery:'Fotos digitais em até 20 dias corridos após o evento',deadline:'Conforme a data do evento; entrega em até 20 dias corridos',description:'Os encontros passam rápido. Vamos registrar as pessoas, os detalhes e os momentos que contam a história dessa celebração.',deliverables:'Cobertura dos momentos principais da festa\nSeleção e tratamento básico das fotografias\nEntrega digital para download',payment:'30% para reservar a data e 70% até 7 dias antes do evento.',notes:'Deslocamento fora de Luís Eduardo Magalhães, álbum impresso e horas extras são cobrados à parte.'},
      {id:'casamento_foto',name:'Casamento · fotografia',title:'Cobertura fotográfica de casamento',price:2490,hours:20,costs:0,billing:'unico',event:true,eventType:'Casamento',coverageHours:8,crew:'1 profissional de fotografia',photoCount:250,photos:'Até 250 fotos selecionadas e tratadas, em galeria digital',videos:'',album:'',extraHour:'R$ 300 por hora adicional de cobertura, sujeita à disponibilidade',eventDelivery:'Fotos digitais em até 30 dias corridos após o evento',deadline:'Conforme a data do casamento; fotos em até 30 dias corridos',description:'Dos preparativos à celebração, a proposta é registrar gestos e encontros para que vocês possam revisitar esse dia.',deliverables:'Cobertura de preparativos, cerimônia e recepção dentro das horas contratadas\nSeleção e tratamento básico das fotografias\nEntrega digital para download',payment:'30% para reservar a data e 70% até 7 dias antes do casamento.',notes:'Segundo fotógrafo, álbum impresso, ensaio pré-casamento, deslocamento e horas extras são opcionais e orçados à parte.'},
      {id:'casamento_completo',name:'Casamento · foto e vídeo',title:'Cobertura de casamento em foto e vídeo',price:6900,hours:40,costs:1500,billing:'unico',event:true,eventType:'Casamento',coverageHours:8,crew:'Equipe prevista: 1 fotógrafo e 1 cinegrafista',photoCount:250,photos:'Até 250 fotos selecionadas e tratadas, em galeria digital',videos:'1 vídeo curto de até 60 segundos e 1 filme de melhores momentos de 3 a 5 minutos',album:'',extraHour:'Hora adicional mediante orçamento por profissional, antes do evento',eventDelivery:'Fotos em até 30 dias e vídeos em até 45 dias corridos após o evento',deadline:'Conforme a data do casamento; prazos específicos para fotos e vídeos',description:'Fotografia e filme se complementam: um preserva os detalhes, o outro devolve o movimento e os sons desse dia.',deliverables:'Cobertura de preparativos, cerimônia e recepção dentro das horas contratadas\nFotografias selecionadas e tratadas\nEdição de vídeo curto e filme de melhores momentos\nEntrega digital para download',payment:'30% para reservar a data e 70% até 7 dias antes do casamento.',notes:'Equipe, disponibilidade e custos de deslocamento devem ser confirmados antes do fechamento. Álbum, drone, cerimônia íntegra e horas extras não estão incluídos.'},
      {id:'corporativo',name:'Evento corporativo · foto e vídeo',title:'Cobertura de evento corporativo',price:2390,hours:17,costs:600,billing:'unico',event:true,eventType:'Evento corporativo',coverageHours:4,crew:'Equipe prevista: 1 fotógrafo e 1 cinegrafista',photoCount:120,photos:'Até 120 fotos selecionadas e tratadas, em galeria digital',videos:'1 vídeo de melhores momentos de até 90 segundos',album:'',extraHour:'Hora adicional mediante orçamento por profissional',eventDelivery:'Fotos em até 10 dias úteis e vídeo em até 15 dias úteis',deadline:'Conforme a data do evento; fotos e vídeo nos prazos combinados',description:'Um registro útil para comunicar o que aconteceu e aproveitar os melhores momentos na divulgação da empresa.',deliverables:'Cobertura de palestras, público e momentos principais dentro das horas contratadas\nSeleção e tratamento básico das fotos\nVídeo curto editado para divulgação\nEntrega digital',payment:'50% na reserva e 50% até a véspera do evento.',notes:'Confirme disponibilidade e custo da equipe. Entrevistas, transmissão ao vivo, postagem em tempo real, deslocamento e horas extras são cobrados à parte.'},
      {id:'evento_video',name:'Evento · vídeo',title:'Cobertura em vídeo de evento',price:1800,hours:16,costs:0,billing:'unico',event:true,eventType:'Evento social',coverageHours:4,crew:'1 cinegrafista',photos:'',videos:'1 teaser vertical de até 60 segundos e 1 vídeo de melhores momentos de até 3 minutos',album:'',extraHour:'R$ 300 por hora adicional de cobertura, sujeita à disponibilidade',eventDelivery:'Vídeos em até 20 dias corridos após o evento',deadline:'Conforme a data do evento; vídeos em até 20 dias corridos',description:'Uma produção para reviver a energia do evento e compartilhar seus momentos mais marcantes.',deliverables:'Captação das principais etapas do evento dentro das horas contratadas\nEdição e correção básica de imagem e som\nEntrega digital dos vídeos finalizados',payment:'30% para reservar a data e 70% até 7 dias antes do evento.',notes:'Não inclui fotografias, gravação integral, drone, transmissão, deslocamento ou arquivos brutos.'},
      {id:'hora_extra',name:'Adicional · hora de cobertura',title:'Hora adicional de cobertura',price:300,hours:2,costs:0,billing:'unico',deadline:'No mesmo evento do pacote principal',description:'Mais tempo para registrar a celebração sem apressar os momentos finais.',deliverables:'1 hora adicional de cobertura com 1 profissional\nTratamento ou edição proporcional ao material captado, conforme o pacote principal',payment:'Adicional aprovado e pago até a data do evento.',notes:'Valor por profissional. Disponibilidade e extensão da equipe devem ser confirmadas antes do evento.'},
      {id:'segundo_fotografo',name:'Adicional · segundo fotógrafo',title:'Segundo fotógrafo',price:1690,hours:8,costs:600,billing:'unico',deadline:'No mesmo evento do pacote principal',description:'Dois pontos de vista para registrar momentos simultâneos e ampliar a cobertura.',deliverables:'1 fotógrafo adicional durante até 8 horas de evento\nFotos selecionadas e tratadas integradas à galeria do pacote principal',payment:'30% na reserva e 70% até 7 dias antes do evento.',notes:'O custo da equipe é uma estimativa: confirme a cotação e a disponibilidade antes de fechar. Deslocamento e hora extra à parte.'},
      {id:'album',name:'Adicional · álbum impresso',title:'Álbum fotográfico impresso',price:1790,hours:6,costs:700,billing:'unico',deadline:'Prazo a confirmar com a gráfica após aprovação do layout',description:'Uma seleção das imagens do evento em um álbum pensado para ser revisto em família.',deliverables:'1 álbum de referência 20 × 30 cm, até 20 páginas\nSeleção de até 60 fotos entre as imagens do pacote principal\nDiagramação e 1 rodada de ajustes antes da impressão',payment:'50% na aprovação do álbum e 50% antes do envio à gráfica.',notes:'Preço e custo da gráfica são estimativas editáveis. Confirme acabamento, frete, páginas adicionais e prazo antes de enviar.'},
      {id:'pre_wedding',name:'Adicional · ensaio pré-casamento',title:'Ensaio pré-casamento',price:790,hours:7,costs:0,billing:'unico',deadline:'Fotos em até 20 dias corridos após o ensaio',description:'Um encontro antes do casamento para registrar o casal com calma, no lugar que faça sentido para sua história.',deliverables:'Até 2 horas de ensaio em 1 local\nAté 50 fotos selecionadas e tratadas\nEntrega digital para download',payment:'50% na reserva da data e 50% antes da entrega.',notes:'Deslocamento, locação e produção de roupas ou maquiagem não incluídos.'},
      {id:'express',name:'Adicional · prévia expressa de fotos',title:'Prévia expressa de fotografias',price:450,hours:3,costs:0,billing:'unico',deadline:'Até 48 horas após o evento',description:'Uma primeira seleção para compartilhar os momentos do evento enquanto a memória ainda está fresca.',deliverables:'Até 15 fotos selecionadas e tratadas em caráter prioritário\nEntrega por link em até 48 horas após o evento',payment:'Pago na contratação do adicional.',notes:'Depende de disponibilidade de agenda e acesso aos arquivos após o evento. A entrega completa segue o prazo do pacote principal.'},
      {id:'drone_evento',name:'Adicional · imagens de drone',title:'Imagens aéreas do evento',price:690,hours:4,costs:100,billing:'unico',deadline:'No mesmo evento; entrega junto com o pacote principal',description:'Imagens aéreas para mostrar a dimensão do lugar e acrescentar outra perspectiva à história do evento.',deliverables:'Captação aérea em até 2 janelas de voo no local\nAté 10 fotografias aéreas tratadas ou trechos selecionados para compor o vídeo contratado',payment:'30% na reserva e 70% até 7 dias antes do evento.',notes:'A execução depende de condições de voo, autorização do espaço, disponibilidade de piloto e equipamento. Não inclui vídeo aéreo independente nem arquivos brutos. Confirme todos os custos antes de fechar.'},
      {id:'drone_avulso',name:'Drone · captação avulsa',title:'Captação aérea avulsa',price:1200,hours:8,costs:200,billing:'unico',deadline:'Até 10 dias úteis após a captação',description:'Uma visão aérea para apresentar um imóvel, empreendimento, espaço ou operação de um jeito que as imagens em solo não mostram.',deliverables:'Planejamento e até 2 horas de captação no local\nAté 15 fotografias aéreas selecionadas e tratadas\n1 vídeo curto de até 60 segundos editado',payment:'50% na reserva e 50% antes da entrega.',notes:'Voo sujeito a condições técnicas e autorizações aplicáveis. Deslocamento, licenças específicas e imagens brutas são orçados à parte.'},
      {id:'logo',name:'Design de logotipo',title:'Design de logotipo',price:2000,hours:18,costs:0,billing:'unico',deadline:'12 a 18 dias úteis após briefing e aprovações',description:'Uma marca visual clara e versátil para representar o negócio em seus principais pontos de contato.',deliverables:'Briefing e direção visual\n1 proposta de logotipo com até 2 rodadas de ajustes\nVersões de cor e aplicação básica\nMini guia de uso da marca',payment:'50% na aprovação e 50% antes da entrega dos arquivos finais.',notes:'Não inclui pesquisa jurídica de marca, registro no INPI ou identidade visual completa.'},
      {id:'identidade',name:'Identidade visual completa',title:'Identidade visual',price:3800,hours:35,costs:0,billing:'unico',deadline:'30 a 45 dias úteis após briefing, conforme aprovações',description:'Um sistema visual coerente para tornar sua marca reconhecível em diferentes canais.',deliverables:'Diagnóstico e direção criativa\nLogotipo principal e versões secundárias\nPaleta de cores, tipografia e elementos de apoio\nGuia de marca e até 3 aplicações demonstrativas\nAté 2 rodadas de ajustes',payment:'50% na aprovação e 50% antes da entrega dos arquivos finais.',notes:'Impressão, registro de marca, embalagens e aplicações adicionais são orçados à parte.'},
      {id:'filmmaker',name:'Produção audiovisual completa',title:'Produção audiovisual personalizada',price:2800,hours:24,costs:0,billing:'unico',deadline:'Cronograma definido após briefing e roteiro',description:'Da ideia à edição, uma produção planejada para comunicar sua mensagem com imagens e som.',deliverables:'Briefing e roteiro para 1 vídeo\nAté 1 diária de captação local com 1 profissional\n1 vídeo final de até 3 minutos\nAté 2 rodadas de ajustes pontuais',payment:'50% na reserva da produção e 50% antes da entrega final.',notes:'Elenco, locução, drone, equipe adicional, estúdio e deslocamento são orçados à parte.'},
      {id:'midia_off',name:'Mídia offline · planejamento e arte',title:'Planejamento e arte de mídia offline',price:890,hours:8,costs:0,billing:'unico',deadline:'Até 10 dias úteis após briefing e medidas finais',description:'Uma peça pensada para comunicar a mensagem da marca com clareza também fora das telas.',deliverables:'Alinhamento de objetivo e formato\n1 arte final para outdoor ou peça impressa em dimensão informada pelo cliente\nArquivo final para produção e 1 rodada de ajustes',payment:'50% na aprovação e 50% antes da entrega da arte final.',notes:'Preço sugerido apenas para criação da arte. Compra de espaço, impressão, instalação e fornecedores são cobrados à parte.'},
      {id:'site',name:'Site institucional',title:'Site institucional',price:2500,hours:24,costs:0,billing:'unico',deadline:'Até 30 dias úteis após briefing e materiais',description:'Um endereço digital para apresentar a empresa, seus serviços e os caminhos de contato.',deliverables:'Até 4 páginas responsivas com conteúdo fornecido pelo cliente\nFormulário simples e botão de WhatsApp\nConfiguração básica de títulos e descrições\n1 rodada de ajustes por página',payment:'50% na aprovação e 50% antes da publicação.',notes:'Hospedagem, domínio, fotos, texto especializado, integrações e manutenção contínua não incluídos.'},
      {id:'portal',name:'Portal personalizado',title:'Portal interno ou externo',price:5000,hours:45,costs:0,billing:'unico',deadline:'Cronograma após levantamento de requisitos',description:'Um portal sob medida para organizar informações, processos ou atendimento em um único lugar.',deliverables:'Levantamento inicial de requisitos\nMapa das páginas e fluxos\nVersão inicial de portal com escopo definido em anexo\nOrientação de uso na entrega',payment:'Condições por etapas após definição do escopo.',notes:'R$ 5.000 é ponto de partida do catálogo da S3. Funcionalidades, usuários, integrações, hospedagem, suporte e segurança exigem orçamento específico.'},
      {id:'social_completo',name:'Social media · gestão ampliada',title:'Gestão de redes sociais',price:1500,hours:15,costs:0,billing:'mensal',deadline:'Ciclo mensal; calendário após briefing',description:'Planejamento e produção contínua para dar consistência à comunicação da marca.',deliverables:'Planejamento mensal para 1 perfil\nAté 12 publicações mensais, entre estáticas e carrosséis simples\nLegendas e agendamento após aprovação\n1 rodada de ajustes por peça\nRelatório mensal',payment:'Mensalidade antecipada no início de cada ciclo.',notes:'Fotos e vídeos produzidos presencialmente, atendimento de DMs e anúncios não incluídos.'},
      {id:'trafego_completo',name:'Tráfego pago · gestão ampliada',title:'Gestão ampliada de tráfego pago',price:2300,hours:22,costs:0,billing:'mensal',deadline:'Configuração inicial e acompanhamento mensal',description:'Uma gestão mais ampla de campanhas, com planejamento, acompanhamento e ajustes ligados aos objetivos do negócio.',deliverables:'Planejamento de até 2 plataformas de anúncio\nEstruturação e gestão de até 4 campanhas ativas\nAcompanhamento semanal e relatório mensal\nReunião mensal de alinhamento',payment:'Mensalidade antecipada. Verba de mídia paga diretamente pelo cliente às plataformas.',notes:'Criação de site, filmagem, atendimento dos leads e investimento em mídia não incluídos. Não há garantia de resultados.'},
      {id:'livre',name:'Serviço personalizado',title:'Serviço personalizado',price:0,hours:0,costs:0,billing:'unico',deadline:'Prazo a definir após briefing',description:'Uma solução construída de acordo com as necessidades específicas deste projeto.',deliverables:'Descreva aqui a primeira entrega\nDescreva aqui a segunda entrega',payment:'Condições a combinar na aprovação.',notes:''}
    ];
    const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(n)||0);
    const formatProposalDate=()=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'long',timeZone:'America/Bahia'}).format(new Date());
    const defaultIntro='Esta proposta reúne os serviços, entregas e condições alinhados para o seu projeto.';
    const makeProposalNumber=()=>`S3-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;
    const eventFields=['eventType','eventDate','venue','coverageHours','crew','photoCount','photos','videos','album','extraHour','eventDelivery'];
    const itemFields=['preset','title','description','deliverables','price','billing','discountType','discountValue','hours','costs','deadline','payment','notes','event',...eventFields];
    let catalogOverrides={};try{const v=JSON.parse(localStorage.getItem('s3-catalogo-v1')||'{}');if(v&&typeof v==='object'&&!Array.isArray(v))catalogOverrides=v}catch(_){}
    const getPreset=id=>{const p=presets.find(x=>x.id===id)||presets[0],override=catalogOverrides[p.id]||{};const result={...p,...override,id:p.id};if(override.photos!==undefined&&override.photoCount===undefined){const n=String(override.photos).match(/\d+/);result.photoCount=n?n[0]:''}return result};
    const clonePreset=(id)=>{const p=getPreset(id);return {...p,discountType:'percent',discountValue:0,uid:crypto.randomUUID?.()||String(Date.now()+Math.random()),eventDate:'',venue:'',event:!!p.event}};
    let state={proposalNumber:makeProposalNumber(),client:'',contact:'',location:'',intro:defaultIntro,introAuto:true,validity:'7',generalNotes:'',items:[clonePreset('presenca')]};
    const save=()=>{try{localStorage.setItem('s3-proposta-rascunho-v2',JSON.stringify(state))}catch(_){}};
    const HISTORY_KEY='s3-propostas-historico-v1';let proposalHistory=[];try{const h=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');if(Array.isArray(h))proposalHistory=h.filter(x=>x&&x.id&&x.data&&Array.isArray(x.data.items)).slice(0,30)}catch(_){}
    function updateHistoryCount(){$('historyCount').textContent=proposalHistory.length?`(${proposalHistory.length})`:''}
    function saveHistory(silent=false){if(!state.items.length){if(!silent)$('status').textContent='Inclua ao menos um serviço antes de salvar no histórico.';return}if(!state.proposalNumber)state.proposalNumber=makeProposalNumber();const entry={id:crypto.randomUUID?.()||String(Date.now()),number:state.proposalNumber,client:state.client.trim()||'Cliente não informado',createdAt:new Date().toISOString(),data:JSON.parse(JSON.stringify(state))};proposalHistory.unshift(entry);proposalHistory=proposalHistory.slice(0,30);try{localStorage.setItem(HISTORY_KEY,JSON.stringify(proposalHistory))}catch(_){if(!silent)$('status').textContent='Não foi possível salvar: o armazenamento deste navegador está cheio.';return}updateHistoryCount();renderHistory();if(!silent)$('status').textContent='Proposta salva no histórico deste navegador.'}
    function renderHistory(){const root=$('historyList');if(!root)return;root.replaceChildren();updateHistoryCount();if(!proposalHistory.length){root.append(el('div',{class:'emptyHistory',text:'Nenhuma proposta salva ainda. Use “Salvar no histórico” depois de revisar uma proposta.'}));return}for(const item of proposalHistory){const row=el('article',{class:'historyItem'}),info=el('div');info.append(el('h3',{text:item.client}),el('div',{class:'historyMeta',text:`${item.number||'Proposta'} · ${new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(item.createdAt))} · ${item.data.items.length} serviço(s)`}));const actions=el('div',{class:'historyActions'});actions.append(el('button',{type:'button',class:'btn','data-history-action':'open','data-history-id':item.id,text:'Abrir'}),el('button',{type:'button',class:'btn danger','data-history-action':'delete','data-history-id':item.id,text:'Excluir'}));row.append(info,actions);root.append(row)}}
    function openHistoryItem(id){const entry=proposalHistory.find(x=>x.id===id);if(!entry)return;if(!window.confirm('Abrir esta cópia e substituir o rascunho atual?'))return;state={...entry.data,introAuto:entry.data.introAuto??(entry.data.intro===defaultIntro),items:entry.data.items.map(x=>({...clonePreset(x.preset||'livre'),...x,uid:clonePreset(x.preset||'livre').uid}))};for(const id of ['client','contact','location','intro','validity','generalNotes'])$(id).value=state[id]||'';render();showTab('proposal');$('status').textContent='Cópia carregada do histórico. Suas alterações não mudam o registro salvo.'}
    const setText=(id,value)=>{$(id).textContent=value||''};
    const el=(tag,attrs={},value)=>{const e=document.createElement(tag);for(const [k,v] of Object.entries(attrs)){if(k==='class')e.className=v;else if(k==='text')e.textContent=v;else e.setAttribute(k,String(v))}if(value!==undefined)e.value=value;return e};
    function field(label,key,item,opts={}){const wrap=el('div',{class:'field'}),id='f-'+item.uid+'-'+key;wrap.append(el('label',{for:id,text:label}));let e=el(opts.tag||'input',{id,'data-uid':item.uid,'data-field':key,...(opts.attrs||{})},item[key]??'');if(key==='event')e.checked=!!item.event;wrap.append(e);return wrap}
    function row(children,columns='two'){const w=el('div',{class:'stack '+columns});children.forEach(x=>w.append(x));return w}
    function selectField(label,key,item,options){const w=field(label,key,item,{tag:'select'}),s=w.querySelector('select');options.forEach(([value,text])=>s.append(el('option',{value,text})));s.value=item[key];return w}
    function eventEditor(item){const box=el('div',{class:'eventBox'});box.hidden=!item.event;box.append(el('h4',{text:'Detalhes da cobertura'}));box.append(el('p',{class:'hint',text:'Preencha apenas o que entrar no contrato. Campo vazio não aparece na proposta. Álbum impresso exige orçamento da gráfica.'}));
      box.append(row([field('Tipo de evento','eventType',item),field('Data do evento','eventDate',item,{attrs:{type:'date'}})]));
      box.append(row([field('Local / cidade','venue',item),field('Horas de cobertura','coverageHours',item,{attrs:{type:'number',min:'0',step:'0.5'}})]));
      box.append(row([field('Equipe prevista','crew',item)] ,'one'));
      box.append(row([field('Quantidade de fotos (opcional)','photoCount',item,{attrs:{type:'number',min:'0',step:'1'}}),field('Descrição da entrega das fotos (opcional)','photos',item)]));
      box.append(row([field('Vídeos entregues (opcional)','videos',item)],'one'));
      box.append(row([field('Álbum: formato, páginas e quantidade (opcional)','album',item),field('Valor da hora extra / regra (opcional)','extraHour',item)]));
      box.append(row([field('Prazo de entrega específico (opcional)','eventDelivery',item)] ,'one'));
      return box}
    function renderEditor(){const root=$('services');root.replaceChildren();state.items.forEach((item,i)=>{
      const card=el('section',{class:'service','data-card':item.uid});let head=el('div',{class:'serviceHead'}),title=el('div');title.append(el('h3',{text:`${i+1}. ${item.title||'Novo serviço'}`}),el('small',{text:item.billing==='mensal'?'Cobrança recorrente mensal':'Projeto ou evento único'}));let tools=el('div');const refresh=el('button',{type:'button',class:'smallBtn','data-action':'refresh','data-uid':item.uid,text:'Usar novo padrão'});const duplicate=el('button',{type:'button',class:'smallBtn','data-action':'duplicate','data-uid':item.uid,text:'Duplicar'});const remove=el('button',{type:'button',class:'smallBtn','data-action':'remove','data-uid':item.uid,text:'Remover'});tools.append(refresh,duplicate,remove);head.append(title,tools);card.append(head);
      card.append(row([selectField('Modelo do serviço','preset',item,presets.map(p=>[p.id,getPreset(p.id).name])),field('Nome que aparecerá na proposta','title',item)]));
      card.append(row([field('Apresentação do serviço / benefício esperado','description',item,{tag:'textarea',attrs:{rows:'2'}})],'one'));
      card.append(row([field('Entregas incluídas — uma por linha','deliverables',item,{tag:'textarea',attrs:{rows:'5'}})],'one'));
      card.append(row([field('Preço (R$)','price',item,{attrs:{type:'number',min:'0',step:'10',inputmode:'decimal'}}),selectField('Tipo de cobrança','billing',item,[['unico','Uma vez'],['mensal','Mensal recorrente']])]));
      card.append(row([field('Desconto','discountValue',item,{attrs:{type:'number',min:'0',step:'1',inputmode:'decimal'}}),selectField('Formato do desconto','discountType',item,[['percent','Percentual (%)'],['fixed','Valor fixo (R$)']])]));
      card.append(el('p',{class:'hint',text:'Em serviços mensais, o desconto vale para cada ciclo; em serviços avulsos, é aplicado uma única vez.'}));
      card.append(row([field('Horas totais de trabalho previstas','hours',item,{attrs:{type:'number',min:'0',step:'0.5'}}),field('Custos externos previstos (R$)','costs',item,{attrs:{type:'number',min:'0',step:'10'}})]));
      card.append(el('div',{class:'economics',id:'economics-'+item.uid}));
      card.append(row([field('Prazo / periodicidade','deadline',item)],'one'));
      card.append(row([field('Condições e opções de pagamento','payment',item,{tag:'textarea',attrs:{rows:'2'}})],'one'));
      const paymentOptions=el('div',{class:'actions',style:'margin:-6px 0 15px'});
      [['50/50','50% na aprovação e 50% antes da entrega.'],['30/70 evento','30% para reservar a data e 70% até 7 dias antes do evento.'],['Mensal antecipado','Mensalidade antecipada no início de cada ciclo.'],['À vista ou parcelas','Opções: Pix à vista na aprovação; ou entrada de 30% e saldo em parcelas combinadas até 7 dias antes do evento. Parcelamento em cartão sujeito às taxas informadas antes da contratação.']].forEach(([label,value])=>paymentOptions.append(el('button',{type:'button',class:'smallBtn','data-action':'payment','data-uid':item.uid,'data-value':value,text:label})));card.append(paymentOptions);
      const check=el('label',{class:'check'}),checkbox=el('input',{type:'checkbox','data-uid':item.uid,'data-field':'event'});checkbox.checked=!!item.event;check.append(checkbox,document.createTextNode('Este serviço inclui cobertura de evento'));card.append(check);
      card.append(eventEditor(item));
      card.append(row([field('Limites e exclusões (opcional)','notes',item,{tag:'textarea',attrs:{rows:'2'}})],'one'));
      root.append(card);updateEconomics(item)
    })}
    function updateEconomics(item){const box=$('economics-'+item.uid);if(!box)return;const price=Math.max(0,(Number(item.price)||0)-lineDiscount(item)),h=Number(item.hours)||0,c=Number(item.costs)||0,rate=h?(price*.8-c)/h:0,min=(h*75+c)/.8;box.classList.toggle('warn',!price||h>0&&rate<75);box.replaceChildren(el('strong',{text:!price?'Defina o preço antes de enviar':!h?'Informe as horas totais':rate<75?'Abaixo da meta interna':'Acima da meta interna'}),document.createTextNode(h?`Com desconto, após reserva de 20% e custos externos: ${money(rate)}/h. Piso indicativo para R$ 75/h: ${money(Math.ceil(min/10)*10)}.`:'Inclua captação, edição, reuniões e deslocamento nas horas.'))}
    function eventDetails(item){if(!item.event)return'';return[
      item.eventType&&`Evento: ${item.eventType}${item.eventDate?' · '+new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC'}).format(new Date(item.eventDate+'T12:00:00Z')):''}`,
      item.venue&&`Local: ${item.venue}`,
      item.coverageHours&&`Cobertura: até ${item.coverageHours} horas`,item.crew&&`Equipe: ${item.crew}`,
      (item.photoCount||item.photos)&&`Fotografias: ${item.photoCount?(item.photos?(/\d+/.test(item.photos)?item.photos.replace(/\d+/,String(item.photoCount)):`Até ${item.photoCount} fotos. ${item.photos}`):`Até ${item.photoCount} fotos selecionadas e tratadas`):item.photos}`,item.videos&&`Vídeos: ${item.videos}`,
      item.album&&`Álbum incluído: ${item.album}`,item.extraHour&&`Hora extra: ${item.extraHour}`,
      item.eventDelivery&&`Entrega: ${item.eventDelivery}`].filter(Boolean).join(' · ')}
    function autoPresentation(){const items=state.items.filter(x=>x.title||x.description);if(!items.length)return defaultIntro;const titles=items.map(x=>x.title.trim()).filter(Boolean),client=state.client.trim()||'seu projeto';const header=items.length===1?`Esta proposta de ${titles[0]||'serviço'} foi preparada para apoiar ${client}.`:`Esta proposta reúne ${titles.slice(0,4).join(', ')} para apoiar os objetivos de ${client}.`;const benefits=items.slice(0,3).map(x=>x.description.trim()).filter(Boolean);return [header,...benefits].join(' ')}
    function lineDiscount(item){const price=Math.max(0,Number(item.price)||0),value=Math.max(0,Number(item.discountValue)||0);return item.discountType==='fixed'?Math.min(price,value):Math.min(price,price*Math.min(value,100)/100)}
    function proposalLocation(){const entered=String(state.location||'').trim();if(entered)return entered;const locations=[...new Set(state.items.map(item=>String(item.venue||'').trim()).filter(Boolean))];return locations.length===1?locations[0]:locations.length>1?locations.slice(0,2).join(' · ')+(locations.length>2?` · +${locations.length-2}`:''):'A combinar com o cliente'}
    function renderCover(){const date=formatProposalDate(),number=state.proposalNumber?'Nº '+state.proposalNumber:'Rascunho';setText('coverClient',state.client.trim()||'Seu projeto');setText('coverLocation',proposalLocation());setText('coverDate',date);setText('coverNumber',number);const list=$('coverServices');list.replaceChildren();const titles=[...new Set(state.items.map(item=>String(item.title||'').trim()).filter(Boolean))];(titles.length?titles.slice(0,4):['Serviços personalizados']).forEach(title=>list.append(el('span',{class:'coverServiceTag',text:title})));if(titles.length>4)list.append(el('span',{class:'coverServiceTag',text:`+ ${titles.length-4} serviço(s)`}))}
    function renderPreview(){if(state.introAuto){state.intro=autoPresentation();$('intro').value=state.intro}renderCover();setText('pClient',state.client.trim()||'Seu cliente');setText('pContact',state.contact.trim()?'A/C '+state.contact.trim():'');setText('pIntro',state.intro.trim()||defaultIntro);setText('pNumber',state.proposalNumber?'Nº '+state.proposalNumber:'');
      const root=$('pServices');root.replaceChildren();let uniqueBase=0,uniqueDiscount=0,monthlyBase=0,monthlyDiscount=0;const showDiscount=state.items.some(item=>lineDiscount(item)>0);$('pDiscountHead').hidden=!showDiscount;$('pServicesTable').classList.toggle('noDiscount',!showDiscount);
      state.items.forEach(item=>{const tr=el('tr'),service=el('td',{class:'serviceCell'}),conditions=el('td',{class:'conditionCell'}),amount=el('td',{class:'amountCell'}),discount=el('td',{class:'discountCell'}),final=el('td',{class:'finalCell'});discount.hidden=!showDiscount;service.append(el('h3',{text:item.title.trim()||'Serviço personalizado'}));if(item.description.trim())service.append(el('p',{text:item.description.trim()}));const list=el('ul');item.deliverables.split('\n').map(x=>x.trim()).filter(Boolean).forEach(x=>list.append(el('li',{text:x})));if(list.children.length)service.append(list);const event=eventDetails(item);if(event)service.append(el('div',{class:'eventDetails',text:event}));conditions.append(el('div',{text:`Prazo: ${item.deadline.trim()||'a combinar'}`}));if(item.payment.trim())conditions.append(el('div',{text:`Pagamento: ${item.payment.trim()}`}));if(item.notes.trim())conditions.append(el('div',{text:`Obs.: ${item.notes.trim()}`}));const base=Math.max(0,Number(item.price)||0),off=lineDiscount(item),net=base-off;amount.append(el('span',{text:money(base)}));if(off>0){discount.append(el('span',{class:'discountLabel',text:'− '+money(off)}));if(item.billing==='mensal')discount.append(el('span',{class:'period',text:'/ mês'}))}else if(showDiscount)discount.append(el('span',{text:'—'}));final.append(el('strong',{text:money(net)}));if(item.billing==='mensal')final.append(el('span',{class:'period',text:'/ mês'}));tr.append(service,conditions,amount,discount,final);root.append(tr);if(item.billing==='mensal'){monthlyBase+=base;monthlyDiscount+=off}else{uniqueBase+=base;uniqueDiscount+=off}});const totals=$('pTotals');totals.replaceChildren();totals.hidden=!state.items.length;
      const unique=uniqueBase-uniqueDiscount,monthly=monthlyBase-monthlyDiscount;
      if(uniqueBase){const block=el('div');block.append(el('small',{text:'Serviços avulsos · '+money(uniqueBase)+(uniqueDiscount?' − desconto '+money(uniqueDiscount):'')}),el('strong',{text:money(unique)}));totals.append(block)}
      if(monthlyBase){const block=el('div');block.append(el('small',{text:'Mensal · '+money(monthlyBase)+(monthlyDiscount?' − desconto '+money(monthlyDiscount):'')}),el('strong',{text:money(monthly)+' / mês'}));totals.append(block)}
      if(!uniqueBase&&!monthlyBase){const block=el('div');block.append(el('small',{text:'Investimento'}),el('strong',{text:'A definir'}));totals.append(block)}
      setText('pValidity',`Proposta válida por ${state.validity||7} dias a partir de ${formatProposalDate()}.`);setText('pGeneralNotes',state.generalNotes.trim());$('pGeneralNotes').hidden=!state.generalNotes.trim();save()
    }
    function render(){renderEditor();renderPreview()}
    function catalogField(label,key,value,options={}){const wrap=el('div',{class:'field'}),id='cat-'+key;wrap.append(el('label',{for:id,text:label}));const e=el(options.tag||'input',{id,'data-catalog-key':key,...(options.attrs||{})},value??'');wrap.append(e);return wrap}
    function catalogSelectField(label,key,value,options){const wrap=catalogField(label,key,'',{tag:'select'}),s=wrap.querySelector('select');options.forEach(([v,t])=>s.append(el('option',{value:v,text:t})));s.value=value;return wrap}
    function refreshOptionLabels(){for(const id of ['newPreset','catalogSelect'])for(const option of $(id).options)option.textContent=getPreset(option.value).name}
    function renderCatalog(){const p=getPreset($('catalogSelect').value),root=$('catalogFields');root.replaceChildren();$('catalogTitle').textContent='Editar: '+p.name;
      root.append(row([catalogField('Nome na lista','name',p.name),catalogField('Título na proposta','title',p.title)]));
      root.append(row([catalogField('Apresentação do serviço / benefício esperado','description',p.description,{tag:'textarea',attrs:{rows:'3'}})],'one'));
      root.append(row([catalogField('Preço padrão (R$)','price',p.price,{attrs:{type:'number',min:'0',step:'10'}}),catalogSelectField('Cobrança padrão','billing',p.billing,[['unico','Uma vez'],['mensal','Mensal recorrente']])]));
      root.append(row([catalogField('Horas de trabalho previstas','hours',p.hours,{attrs:{type:'number',min:'0',step:'0.5'}}),catalogField('Custos externos previstos (R$)','costs',p.costs,{attrs:{type:'number',min:'0',step:'10'}})]));
      root.append(row([catalogField('Entregas padrão — uma por linha','deliverables',p.deliverables,{tag:'textarea',attrs:{rows:'5'}})],'one'));
      root.append(row([catalogField('Prazo padrão','deadline',p.deadline)],'one'));
      root.append(row([catalogField('Condições de pagamento padrão','payment',p.payment,{tag:'textarea',attrs:{rows:'2'}})],'one'));
      root.append(row([catalogField('Limites e exclusões','notes',p.notes,{tag:'textarea',attrs:{rows:'2'}})],'one'));
      const check=el('label',{class:'check'}),input=el('input',{type:'checkbox','data-catalog-key':'event'});input.checked=!!p.event;check.append(input,document.createTextNode('Mostrar campos de cobertura de evento'));root.append(check);
      const box=el('div',{class:'eventBox',id:'catalogEventFields'});box.hidden=!p.event;box.append(el('h4',{text:'Padrões da cobertura'}),el('p',{class:'hint',text:'A quantidade de fotos e os demais detalhes podem ser ajustados novamente em cada proposta.'}));
      box.append(row([catalogField('Tipo de evento','eventType',p.eventType),catalogField('Horas de cobertura','coverageHours',p.coverageHours,{attrs:{type:'number',min:'0',step:'0.5'}})]));
      box.append(row([catalogField('Equipe prevista','crew',p.crew)],'one'));
      box.append(row([catalogField('Quantidade de fotos','photoCount',p.photoCount,{attrs:{type:'number',min:'0',step:'1'}}),catalogField('Descrição da entrega das fotos','photos',p.photos,{tag:'textarea',attrs:{rows:'2'}})]));
      box.append(row([catalogField('Quantidade e duração de vídeos','videos',p.videos,{tag:'textarea',attrs:{rows:'2'}})],'one'));
      box.append(row([catalogField('Álbum incluído (opcional)','album',p.album),catalogField('Valor da hora extra (opcional)','extraHour',p.extraHour)]));
      box.append(row([catalogField('Prazo específico de entrega','eventDelivery',p.eventDelivery)],'one'));root.append(box)
    }
    function showTab(name){for(const [key,id,tab] of [['proposal','proposalTab','tabProposal'],['catalog','catalogTab','tabCatalog'],['ai','aiTab','tabAI'],['history','historyTab','tabHistory']]){$(id).hidden=name!==key;$(tab).setAttribute('aria-selected',String(name===key))}if(name==='catalog')renderCatalog();if(name==='history')renderHistory();window.scrollTo({top:0,behavior:'auto'})}
    presets.forEach(p=>{for(const id of ['newPreset','catalogSelect'])$(id).append(el('option',{value:p.id,text:getPreset(p.id).name}))});updateHistoryCount();
    $('tabProposal').addEventListener('click',()=>showTab('proposal'));
    $('tabCatalog').addEventListener('click',()=>showTab('catalog'));
    $('tabAI').addEventListener('click',()=>showTab('ai'));
    $('tabHistory').addEventListener('click',()=>showTab('history'));
    $('historyList').addEventListener('click',e=>{const b=e.target.closest('button[data-history-action]');if(!b)return;const id=b.dataset.historyId;if(b.dataset.historyAction==='open')openHistoryItem(id);if(b.dataset.historyAction==='delete'){proposalHistory=proposalHistory.filter(x=>x.id!==id);try{localStorage.setItem(HISTORY_KEY,JSON.stringify(proposalHistory))}catch(_){}renderHistory()}});
    $('catalogSelect').addEventListener('change',()=>{renderCatalog();$('catalogStatus').textContent='' });
    $('catalogFields').addEventListener('input',e=>{const key=e.target.dataset.catalogKey;if(!key)return;const id=$('catalogSelect').value;catalogOverrides[id]={...(catalogOverrides[id]||{}),[key]:key==='event'?e.target.checked:e.target.value};try{localStorage.setItem('s3-catalogo-v1',JSON.stringify(catalogOverrides))}catch(_){}if(key==='event')$('catalogEventFields').hidden=!e.target.checked;if(key==='name'){refreshOptionLabels();$('catalogTitle').textContent='Editar: '+e.target.value}renderEditor();$('catalogStatus').textContent='Padrão salvo neste navegador. Novos itens usarão estes dados.'});
    $('restorePreset').addEventListener('click',()=>{delete catalogOverrides[$('catalogSelect').value];try{localStorage.setItem('s3-catalogo-v1',JSON.stringify(catalogOverrides))}catch(_){}refreshOptionLabels();renderCatalog();renderEditor();$('catalogStatus').textContent='Padrão original restaurado para este serviço.'});
    let aiDraft=null;
    fetch('/admin/ai-status.php').then(r=>r.json()).then(x=>{if(!x.ready)$('aiStatus').textContent='A geração por IA abre o aplicativo de propostas publicado. Os rascunhos de cada endereço são separados.'}).catch(()=>{$('aiStatus').textContent='Não foi possível verificar a conexão da IA.'});
    $('aiBrief').addEventListener('input',()=>{aiDraft=null;$('aiResult').hidden=true});
    $('aiGenerate').addEventListener('click',async()=>{
      window.open('https://s3-propostas-douglas.dougleisouza613.chatgpt.site/', '_blank', 'noopener'); return;

      const brief=$('aiBrief').value.trim();if(brief.length<15){$('aiStatus').textContent='Descreva o serviço em pelo menos 15 caracteres.';return}
      aiDraft=null;$('aiResult').hidden=true;$('aiGenerate').disabled=true;$('aiGenerate').textContent='Gerando…';$('aiStatus').textContent='Analisando o resumo e os padrões do catálogo…';
      try{const catalog=presets.map(p=>getPreset(p.id));const response=await fetch('/api/ai/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({brief,catalog})});const data=await response.json();if(!response.ok)throw Error(data.error||'Não foi possível gerar a proposta.');aiDraft=data;
        const summary=$('aiSummary');summary.replaceChildren(el('p',{text:(data.client?'Cliente: '+data.client+' · ':'')+(data.location?'Local: '+data.location+' · ':'')+(data.intro||'')}));
        const cards=$('aiCards');cards.replaceChildren();for(const item of data.services){const card=el('div',{class:'aiCard'});card.append(el('h3',{text:item.title}),el('p',{text:item.description}),el('p',{text:`${money(item.price)}${item.billing==='mensal'?' / mês':''} · ${item.deadline||'Prazo a combinar'}`}),el('p',{text:'Pagamento: '+(item.payment||'A combinar')}));if(item.deliverables)card.append(el('p',{text:'Entregas: '+item.deliverables.split('\n').join(' · ')}));if(item.defaults.includes('price')||item.defaults.includes('deadline')||item.defaults.includes('payment'))card.append(el('p',{class:'hint',text:'Preço, prazo ou pagamento ausente no resumo: aplicado o padrão do catálogo.'}));cards.append(card)}
        const warnings=$('aiWarnings');warnings.replaceChildren(...(data.warnings||[]).map(w=>el('p',{text:w})));$('aiResult').hidden=false;$('aiStatus').textContent='Rascunho gerado. Confira cada serviço antes de usar.';
      }catch(error){$('aiStatus').textContent=error.message||'Não foi possível gerar a proposta.'}finally{$('aiGenerate').disabled=false;$('aiGenerate').textContent='Gerar rascunho com IA'}
    });
    function applyAi(replace){if(!aiDraft)return;const items=aiDraft.services.map(item=>({...clonePreset(item.preset),...item,uid:clonePreset(item.preset).uid}));if(replace){state.items=items;state.proposalNumber=makeProposalNumber()}else state.items.push(...items);if(replace)state.location=aiDraft.location||'';else if(aiDraft.location&&!state.location)state.location=aiDraft.location;if(aiDraft.client&&(replace||!state.client))state.client=aiDraft.client;if(aiDraft.intro&&(replace||state.introAuto)){state.intro=aiDraft.intro;state.introAuto=false}for(const id of ['client','location','intro'])$(id).value=state[id]||'';render();saveHistory(true);showTab('proposal');$('status').textContent='Proposta da IA adicionada ao histórico. Revise e salve novamente se fizer alterações.'}
    $('aiReplace').addEventListener('click',()=>applyAi(true));$('aiAppend').addEventListener('click',()=>applyAi(false));
    for(const id of ['client','contact','location','intro','validity','generalNotes'])$(id).addEventListener('input',e=>{state[id]=e.target.value;if(id==='intro')state.introAuto=false;renderPreview()});
    $('services').addEventListener('input',e=>{const node=e.target,uid=node.dataset.uid,key=node.dataset.field;if(!uid||!key||key==='preset')return;const item=state.items.find(x=>x.uid===uid);if(!item)return;item[key]=key==='event'?node.checked:node.value;if(key==='title'||key==='billing'){const card=node.closest('.service');card.querySelector('.serviceHead h3').textContent=`${state.items.indexOf(item)+1}. ${item.title||'Novo serviço'}`;card.querySelector('.serviceHead small').textContent=item.billing==='mensal'?'Cobrança recorrente mensal':'Projeto ou evento único'}if(key==='event')node.closest('.service').querySelector('.eventBox').hidden=!item.event;if(['hours','costs','price','discountValue','discountType'].includes(key))updateEconomics(item);renderPreview()});
    $('services').addEventListener('change',e=>{const node=e.target,uid=node.dataset.uid;if(!uid)return;const item=state.items.find(x=>x.uid===uid);if(!item)return;if(node.dataset.field==='preset'){const previous={uid:item.uid};const fresh=clonePreset(node.value);Object.assign(item,fresh,previous);render()}else if(node.dataset.field==='event'){item.event=node.checked;node.closest('.service').querySelector('.eventBox').hidden=!item.event;renderPreview()}});
    $('services').addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const index=state.items.findIndex(x=>x.uid===b.dataset.uid);if(index<0)return;
      if(b.dataset.action==='remove'){state.items.splice(index,1);render()}
      if(b.dataset.action==='duplicate'){state.items.splice(index+1,0,{...state.items[index],uid:clonePreset('livre').uid});render()}
      if(b.dataset.action==='refresh'){const prior=state.items[index],newItem=clonePreset(prior.preset);state.items[index]={...newItem,uid:prior.uid,eventDate:prior.eventDate||'',venue:prior.venue||''};render();$('status').textContent='Padrão atualizado neste item. Revise preço e condições antes de enviar.'}
      if(b.dataset.action==='payment'){state.items[index].payment=b.dataset.value;render()}
    });
    $('add').addEventListener('click',()=>{state.items.push(clonePreset($('newPreset').value));render();$('services').lastElementChild?.scrollIntoView({block:'center',behavior:'smooth'})});
    $('saveHistory').addEventListener('click',()=>saveHistory());
    $('print').addEventListener('click',()=>{if(!state.items.length){$('status').textContent='Inclua ao menos um serviço antes de salvar a proposta.';return}if(state.items.some(x=>!Number(x.price))){$('status').textContent='Defina o preço de todos os serviços antes de salvar a proposta.';return}renderPreview();window.print()});
    $('copy').addEventListener('click',async()=>{const lines=[`Olá, ${state.contact.trim()||state.client.trim()||'tudo bem'}! Preparei uma proposta da S3 Mídia para ${state.client.trim()||'você'}.`,'',...state.items.map(x=>{const off=lineDiscount(x),final=Math.max(0,Number(x.price)||0)-off;return`${x.title}: ${money(final)}${x.billing==='mensal'?' por mês':''}${off?` (desconto de ${money(off)}${x.billing==='mensal'?' ao mês':''})`:''}\n${x.deliverables.split('\n').filter(Boolean).map(y=>'• '+y.trim()).join('\n')}\nPagamento: ${x.payment}`}),'',`Validade: ${state.validity||7} dias. Posso explicar os próximos passos?`];try{await navigator.clipboard.writeText(lines.join('\n'));$('status').textContent='Resumo copiado. Revise antes de enviar.'}catch(_){$('status').textContent='Não foi possível copiar neste navegador; use o PDF.'}});
    $('clear').addEventListener('click',()=>{try{localStorage.removeItem('s3-proposta-rascunho-v2');localStorage.removeItem('s3-proposta-rascunho-v1')}catch(_){}state={proposalNumber:makeProposalNumber(),client:'',contact:'',location:'',intro:defaultIntro,introAuto:true,validity:'7',generalNotes:'',items:[clonePreset('presenca')]};for(const id of ['client','contact','location','intro','validity','generalNotes'])$(id).value=state[id]||'';render();$('status').textContent='Rascunho limpo.'});
    let saved;try{saved=JSON.parse(localStorage.getItem('s3-proposta-rascunho-v2')||'null');if(saved&&Array.isArray(saved.items)){saved.items=saved.items.filter(x=>x&&typeof x.uid==='string').map(x=>{const item={...clonePreset(x.preset||'livre'),...x};if(x.photoCount===undefined&&x.photos){const n=String(x.photos).match(/\d+/);item.photoCount=n?n[0]:''}return item});state={...state,...saved};if(saved.introAuto===undefined)state.introAuto=saved.intro===defaultIntro}else{const old=JSON.parse(localStorage.getItem('s3-proposta-rascunho-v1')||'null');if(old&&old.preset){const item=clonePreset(old.preset);for(const key of itemFields)if(old[key]!==undefined)item[key]=old[key];state={client:old.client||'',contact:old.contact||'',location:'',intro:old.goal||defaultIntro,introAuto:!old.goal,validity:old.validity||'7',generalNotes:'',items:[item]}}}}catch(_){}
    for(const id of ['client','contact','location','intro','validity','generalNotes'])$(id).value=state[id]||'';render();
    if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'preparar_proposta_s3',title:'Preparar proposta S3',description:'Preenche o rascunho local com cliente e uma lista de serviços; não envia ao cliente.',inputSchema:{type:'object',properties:{cliente:{type:'string'},servicos:{type:'array',minItems:1,items:{type:'string',enum:presets.map(p=>p.id)}}},required:['cliente','servicos'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.cliente!=='string'||!input.cliente.trim()||!Array.isArray(input.servicos)||!input.servicos.length||input.servicos.some(id=>!presets.some(p=>p.id===id)))throw Error('Informe cliente e serviços válidos.');state.client=input.cliente.trim();state.items=input.servicos.map(clonePreset);$('client').value=state.client;render();return{cliente:state.client,servicos:state.items.map(x=>x.title),estado:'rascunho local atualizado'}}})).catch(()=>{})}catch(_){}}
  </script>
</body>
</html>

